---
- name: Install Docker on Jenkins and Docker Servers
  hosts: all
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

- name: Add Ubuntu to Docker Group (Only on Docker Server)
  hosts: docker_host
  become: yes

  tasks:
    - name: Add Ubuntu user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reboot to apply group changes
      reboot:
        msg: "Rebooting to apply Docker group changes"
        connect_timeout: 5
        reboot_timeout: 600